# Originally generated by pip2nix 0.8.0.dev1, then modified by me (Tayou)
# See https://github.com/nix-community/pip2nix

{ pkgs, lib, pythonPackages }:

{
  "libigl" = pythonPackages.buildPythonPackage rec {
    pname = "libigl";
    version = "2.5.1";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/41/4efcb97254fd57e572ba7f419108968663a872ca6f1c584b7f012da0d3bd/libigl-2.6.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl";
      sha256 = "sha256-JWl7++oglX2beumr/5WlYCl7M7+SuiVbio8biZDA/Ls=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [
      pkgs.python3
    ];
    checkInputs = [];
    nativeBuildInputs = [
      pkgs.unzip
    ];
    propagatedBuildInputs = [
      pythonPackages.numpy
      pythonPackages.scipy
    ];
  };
  "robust-laplacian" = pythonPackages.buildPythonPackage rec {
    pname = "robust-laplacian";
    version = "1.0.0";
    src = pkgs.fetchPypi {
      pname = "robust_laplacian";
      version = version;
      sha256 = "sha256-oA18Il5AtvmhucjeDFy1Ha3TU2fj/mGyZaRkMWW04I0=";
    };
#    src = pkgs.fetchFromGitHub {
#      owner = "nmwsharp";
#      repo = "robust-laplacians-py";
#      rev = "b2721e244e82cec56af90de626cee717326195af";
#      sha256 = "sha256-CERmB+VFsYyOtCpu0oOSyTOh8zO99zhImT47cyBH3co=";
#      fetchSubmodules = true;
#    };
    preBuild = "cd ..";

    pyproject = true;
    doCheck = false;

    build-system = with pythonPackages; [ scikit-build-core ];
    dependencies = with pythonPackages; [
      numpy
    ];

    nativeBuildInputs = [
      pkgs.cmake
      pkgs.ninja
    ];

    propagatedBuildInputs = [
      pythonPackages.numpy
    ];

    cmakeFlags = [
      "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
    ];
  };
}
