# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "libigl" = super.buildPythonPackage rec {
    pname = "libigl";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/5a/de034dd2ee178394b7de59d94a32c74a9c475f98f9c56211362a2497513d/libigl-2.5.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-i0EiZpz12AowTQic8JTOHHjP0JzFQmNH+tmWHYAxAEU=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [
      pkgs.python3
    ];
    checkInputs = [];
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    propagatedBuildInputs = [
      self."numpy"
      self."scipy"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robust-laplacian" = super.buildPythonPackage rec {
    pname = "robust-laplacian";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/72/4a/8fb9dce55fcae27db44f1d3215887b938dbc3d2eb02858b8012de2b83892/robust_laplacian-1.0.0-pp310-pypy310_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-ZLyr7Juof25GqQUJ1B0nr9ShUkuj7tOR7YI2HnupBjw=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "scipy" = super.buildPythonPackage rec {
    pname = "scipy";
    version = "1.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/fe/9c4361e7ba2927074360856db6135ef4904d505e9b3afbbcb073c4008328/scipy-1.15.3-cp313-cp313t-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-nbmEY5iH49/7OSjRGBRf/kDv8vpAyyQaMG7FfCGeu7s=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
}
